version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - auth

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  auth:
    build: ./auth
    ports:
      - "4000:4000"
    depends_on:
      - database

  database:
    build: ./database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
